### ISSUE TITLE
Định nghĩa của Hive và kiến trúc của Hive

### ISSUE THREAD

**Issue by thuantn1510** [taytran1510/ProjectCC#9]
tìm hiểu thế nào là apache hive và kiến trúc của hive trong hệ thống hadoop

**Comment by taytran1510** [comment]
[Uploading HIVE-là-gì.docx…]()

**Comment by thuantn1510** [comment]
[HIVE-là-gì.docx](https://github.com/taytran1510/ProjectCC/files/6377324/HIVE-la-gi.docx)
